version: 0.2

phases:
  install:
    commands:
      - echo "Checking Terraform version"
      - terraform version

  build:
    commands:
      - pwd
      - ls -la
      - cd terraform/aws-quick
      - terraform init
      - terraform plan
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
